# yarn install
# yarn tsc
# yarn build
#
# yarn build-image

FROM node:18-bullseye-slim

WORKDIR /app
RUN apt-get update \
    && apt-get install -y procps \
    && apt-get install -y curl \
    && apt-get install -y psmisc \
    && apt-get install -y git
RUN apt-get install -y python3 python3-pip

RUN pip3 install mkdocs-techdocs-core==1.1.7

COPY . .

RUN yarn install
# RUN yarn build:all

# From here on we use the least-privileged `node` user to run the backend.
# USER node

EXPOSE 3000 7007