name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Login to AWS ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 597701726802.dkr.ecr.us-east-1.amazonaws.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Build and Push Docker Image
        run: |
          docker build -t 597701726802.dkr.ecr.us-east-1.amazonaws.com/backstage-demo-prod:latest --build-arg BASE_URL='backstage-demo.iampeto.com' .
          docker push 597701726802.dkr.ecr.us-east-1.amazonaws.com/backstage-demo-prod:latest
